// Real ISO 3166-1 country list (English short names, alpha-2 codes),
// covering the 193 UN member states plus Palestine and Vatican City
// (Holy See) -- both commonly included in general-purpose "list of
// countries" references. `euMember: true` marks the 27 current EU member
// states. Used by the "Where does this operate?" jurisdiction picker in
// app/screens/KnowledgeBaseScreen.js.
//
// Codes match specific_regulations' informal jurisdiction convention
// (EU | US | US-CA | UK | CN | SG ...) so a prefix match in
// app/lib/tagger.js works directly -- e.g. a use case operating in
// Germany ("DE") should also boost EU-wide regulations, which
// expandJurisdictionCodes() below handles.

export const EU_OPTION = { code: "EU", name: "European Union (all member states)" };
export const OTHER_OPTION = { code: "OTHER", name: "Other / not sure" };

export const COUNTRIES = [
  // Africa
  { code: "DZ", name: "Algeria" },
  { code: "AO", name: "Angola" },
  { code: "BJ", name: "Benin" },
  { code: "BW", name: "Botswana" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "CM", name: "Cameroon" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo, Republic of the" },
  { code: "CD", name: "Congo, Democratic Republic of the" },
  { code: "DJ", name: "Djibouti" },
  { code: "EG", name: "Egypt" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GH", name: "Ghana" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "CI", name: "Ivory Coast" },
  { code: "KE", name: "Kenya" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "ML", name: "Mali" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibia" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "RW", name: "Rwanda" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SN", name: "Senegal" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "SD", name: "Sudan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TG", name: "Togo" },
  { code: "TN", name: "Tunisia" },
  { code: "UG", name: "Uganda" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  // Americas
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "BS", name: "Bahamas" },
  { code: "BB", name: "Barbados" },
  { code: "BZ", name: "Belize" },
  { code: "BO", name: "Bolivia" },
  { code: "BR", name: "Brazil" },
  { code: "CA", name: "Canada" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "SV", name: "El Salvador" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "JM", name: "Jamaica" },
  { code: "MX", name: "Mexico" },
  { code: "NI", name: "Nicaragua" },
  { code: "PA", name: "Panama" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "SR", name: "Suriname" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "VE", name: "Venezuela" },
  // Asia
  { code: "AF", name: "Afghanistan" },
  { code: "AM", name: "Armenia" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BT", name: "Bhutan" },
  { code: "BN", name: "Brunei" },
  { code: "KH", name: "Cambodia" },
  { code: "CN", name: "China" },
  { code: "GE", name: "Georgia" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IL", name: "Israel" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Lebanon" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "MN", name: "Mongolia" },
  { code: "MM", name: "Myanmar" },
  { code: "NP", name: "Nepal" },
  { code: "KP", name: "North Korea" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PS", name: "Palestine" },
  { code: "PH", name: "Philippines" },
  { code: "QA", name: "Qatar" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SG", name: "Singapore" },
  { code: "KR", name: "South Korea" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SY", name: "Syria" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  // Europe
  { code: "AL", name: "Albania" },
  { code: "AD", name: "Andorra" },
  { code: "AT", name: "Austria", euMember: true },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium", euMember: true },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BG", name: "Bulgaria", euMember: true },
  { code: "HR", name: "Croatia", euMember: true },
  { code: "CY", name: "Cyprus", euMember: true },
  { code: "CZ", name: "Czechia", euMember: true },
  { code: "DK", name: "Denmark", euMember: true },
  { code: "EE", name: "Estonia", euMember: true },
  { code: "FI", name: "Finland", euMember: true },
  { code: "FR", name: "France", euMember: true },
  { code: "DE", name: "Germany", euMember: true },
  { code: "GR", name: "Greece", euMember: true },
  { code: "HU", name: "Hungary", euMember: true },
  { code: "IS", name: "Iceland" },
  { code: "IE", name: "Ireland", euMember: true },
  { code: "IT", name: "Italy", euMember: true },
  { code: "LV", name: "Latvia", euMember: true },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania", euMember: true },
  { code: "LU", name: "Luxembourg", euMember: true },
  { code: "MT", name: "Malta", euMember: true },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "ME", name: "Montenegro" },
  { code: "NL", name: "Netherlands", euMember: true },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "PL", name: "Poland", euMember: true },
  { code: "PT", name: "Portugal", euMember: true },
  { code: "RO", name: "Romania", euMember: true },
  { code: "RU", name: "Russia" },
  { code: "SM", name: "San Marino" },
  { code: "RS", name: "Serbia" },
  { code: "SK", name: "Slovakia", euMember: true },
  { code: "SI", name: "Slovenia", euMember: true },
  { code: "ES", name: "Spain", euMember: true },
  { code: "SE", name: "Sweden", euMember: true },
  { code: "CH", name: "Switzerland" },
  { code: "UA", name: "Ukraine" },
  { code: "GB", name: "United Kingdom" },
  { code: "VA", name: "Vatican City" },
  // Oceania
  { code: "AU", name: "Australia" },
  { code: "FJ", name: "Fiji" },
  { code: "KI", name: "Kiribati" },
  { code: "MH", name: "Marshall Islands" },
  { code: "FM", name: "Micronesia" },
  { code: "NR", name: "Nauru" },
  { code: "NZ", name: "New Zealand" },
  { code: "PW", name: "Palau" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "WS", name: "Samoa" },
  { code: "SB", name: "Solomon Islands" },
  { code: "TO", name: "Tonga" },
  { code: "TV", name: "Tuvalu" },
  { code: "VU", name: "Vanuatu" },
];

/** Given the raw codes a submitter picked (countries, "EU", "OTHER"),
 * returns the effective set to bias matching with -- any selected EU
 * member country implicitly also boosts EU-wide regulations, since
 * operating in France means EU AI Act exposure too, not just France's own
 * (currently untracked at country level) regulations. */
export function expandJurisdictionCodes(selectedCodes) {
  const expanded = new Set(selectedCodes);
  for (const code of selectedCodes) {
    const country = COUNTRIES.find((c) => c.code === code);
    if (country?.euMember) expanded.add("EU");
  }
  return Array.from(expanded);
}
