-- Lets the trend-based horizon forecaster (ingestion/generate_horizon_forecasts.py)
-- safely re-run without duplicating rows: one forecast per
-- (target_jurisdiction, origin_driver_category) pair it has ever generated,
-- upserted by this key on every run as the underlying trend data changes.
-- NULL for the original hand-seeded rows in database/seed.sql -- this only
-- tags rows this script itself created/owns.

ALTER TABLE regulatory_horizon_forecast ADD COLUMN IF NOT EXISTS trend_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_horizon_trend_key ON regulatory_horizon_forecast(trend_key)
    WHERE trend_key IS NOT NULL;

COMMENT ON COLUMN regulatory_horizon_forecast.trend_key IS
    'Set only on rows generated by ingestion/generate_horizon_forecasts.py from real origin_driver_trend_summary data (format: trend:{jurisdiction}:{origin_driver_category}). NULL for hand-authored seed rows.';
